### ISSUE TITLE
"$JAVA_OPTS" preventing the echo_service to start

### ISSUE THREAD

**Issue by spicoflorin** [ExampleDriven/spring-boot-docker-example#2]
Hi!
  The echo-service does't start due to 
echo-service_1   | Error: Could not find or load main class $JAVA_OPTS
springbootdockerexample_echo-service_1 exited with code 1. 
The generated  Dockerfile was:
FROM java:8
ENV JAVA_OPTS ""
ADD /echo-service-0.0.1-SNAPSHOT.jar //
ENTRYPOINT ["java", "$JAVA_OPTS", "-jar", "/echo-service-0.0.1-SNAPSHOT.jar", "-Xdebug -Xrunjdwp:server=y,transport=dt_socket,suspend=n"]

**Comment by mustafa-ammari** [comment]
Hello
I have the same issue

**Comment by szantopeter** [comment]
Thanks for reporting, I fixed it!
